# Generated by Django 5.1.6 on 2025-03-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mymodel',
        ),
    ]
