# Generated by Django 5.1.6 on 2025-03-19 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('old', 'Old')], default='new', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100, null=True)),
                ('detail', models.CharField(choices=[('Sold', 'Sold'), ('not_sold', 'Not Sold'), ('deleted', 'Deleted')], default='Sold', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.products')),
                ('Brand_name', models.CharField(max_length=200)),
                ('Bicycle_category', models.CharField(max_length=100)),
            ],
            bases=('categories.products',),
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.products')),
                ('km_driven', models.CharField(max_length=10)),
                ('Brand', models.CharField(max_length=200)),
                ('Year', models.DateField()),
            ],
            bases=('categories.products',),
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.products')),
                ('km_driven', models.CharField(max_length=10)),
                ('mileage', models.CharField(max_length=11)),
                ('variant', models.CharField(max_length=12)),
            ],
            bases=('categories.products',),
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.products')),
                ('Electrnics_type', models.CharField(max_length=200)),
                ('Warranty_left', models.CharField(default='Out Of warranty', max_length=200)),
                ('Brand_name', models.CharField(max_length=200)),
            ],
            bases=('categories.products',),
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.products')),
                ('Furniture_type', models.CharField(max_length=200)),
                ('wood_name', models.CharField(max_length=100)),
            ],
            bases=('categories.products',),
        ),
        migrations.AddField(
            model_name='products',
            name='c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Product_images/')),
                ('P', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.products')),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100)),
                ('U_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory'),
        ),
        migrations.CreateModel(
            name='SubCategoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubcategoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.products')),
                ('subcategorydetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategorydetails')),
            ],
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['Product_name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['price'], name='price_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['created_at'], name='created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['status', 'detail'], name='status_avail_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['state', 'city'], name='location_idx'),
        ),
    ]
