# Generated by Django 5.1.6 on 2025-03-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='products',
            name='product_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='products',
            name='price_idx',
        ),
        migrations.RemoveIndex(
            model_name='products',
            name='created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='products',
            name='status_avail_idx',
        ),
        migrations.RemoveIndex(
            model_name='products',
            name='location_idx',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='c',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='s',
            new_name='subcategory',
        ),
        migrations.RemoveField(
            model_name='products',
            name='detail',
        ),
        migrations.AddField(
            model_name='products',
            name='availability',
            field=models.CharField(choices=[('Sold', 'Sold'), ('not_sold', 'Not Sold'), ('deleted', 'Deleted')], default='Sold', max_length=10),
        ),
    ]
