# Generated by Django 5.1.6 on 2025-03-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_products_display_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='display_photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
